name: qme
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^2.0.0
  bloc: ^6.1.0
  cached_network_image: ^2.2.0+1
  calendar_strip: ^1.0.7
  carousel_pro: ^1.0.0
  checkbox_formfield: ^0.1.0+3
  cloud_firestore: ^0.13.7
  country_code_picker: ^1.3.12+1
  cupertino_icons: ^0.1.2
  equatable: ^1.2.5
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.4
  firebase_messaging: ^6.0.1
  firebase_remote_config: ^0.3.1
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.1.0
  flutter_layout_grid: ^0.10.1
  flutter_rating_bar: ^3.0.1+1
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.8.1
  geocoding: ^1.0.5
  geolocator: ^6.1.13
  google_fonts: ^1.1.0
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  http: ^0.12.1
  icon_shadow: ^1.0.1
  intl: ^0.16.1
  intro_slider: ^2.3.1
  keyboard_avoider: ^0.1.2
  logger: ^0.9.1
  maps_launcher: ^1.2.2+1
  marquee_widget: ^0.8.0
  ordered_set: ^2.0.0
  path_drawing: ^0.4.1
  pin_code_fields: ^5.0.1
  provider: ^4.1.1
  shimmer: ^1.1.1
  url_launcher: ^5.5.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.10.1
  hive_generator: ^0.7.1
  test: ^1.15.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-85-Heavy.ttf
    - family: AvenirLight
      fonts:
        - asset: fonts/Avenir-35-Light.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/temp/otpSvg.svg
    - assets/temp/getStarted.svg
    - assets/temp/users.svg
    - assets/temp/introSlider1.png
    - assets/temp/introSlider2.png
    - assets/temp/introSlider3.png
    - assets/blue-tick.flr
    - assets/my-bookings.png
    - assets/no-bookings.jpg
    - assets/images/aboutus.png
    - assets/images/contactus.png
    - assets/images/man.png
    - assets/images/wantlist.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
